fix(cycle): account for re-entry of all mappables
zefiros-software/axioms pull request #58
Opened 2022-02-16 07:13 UTC by MickVanDuijn

2022-02-17 18:18 UTC, pevisscher commented on src/generator/cycle/cycle.spec.ts
> +        expect(collect(take(n, cycle(gen)))).toHaveLength(n)
```suggestion
        return collect(take(n, cycle(gen))).length === n
```

2022-02-17 18:19 UTC, pevisscher commented on src/generator/cycle/cycle.spec.ts
> +        expect(collect(take(n, cycle(gen)))).toHaveLength(0)
```suggestion
        return collect(take(n, cycle(gen))).length === 0
```

2022-02-17 18:19 UTC, pevisscher commented on src/generator/cycle/cycle.spec.ts
> +        expect(collect(take(n, cycle(gen)))).toHaveLength(n)
or even `length()` could be used here, but is not necessarily cleaner

2022-02-17 18:22 UTC, pevisscher commented on src/generator/cycle/cycle.ts
> +        consecutiveEmptyCycles = cycleSize === 0 ? consecutiveEmptyCycles + 1 : 0
```suggestion
        consecutiveEmptyCycles += cycleSize === 0 ? 1 : 0
```

2022-02-17 18:24 UTC, pevisscher commented on src/generator/cycle/cycle.ts
> +export function* cycle<T>(xs: Mappable<T>, maxConsecutiveEmptyCycles = 10000): InfiniteGenerator<T> {
why do we want this safety? nothing prevents you from writing an endless while too - but this adds a side effect to the function

2022-02-17 18:28 UTC, pevisscher commented on src/random/types/mappable/mappable.ts
> +    return oneOf<Arbitrary<Mappable<T>>[]>(
I _think_ we may need to make the items applicative here. Also, I don't think you want to have the `Arbitrary<Mappable<T>>` type, but just a simple `Arbitrary<T>` and compose it with an `array` arbitrary, we're only changing the interface; not the underlying values.

2022-02-17 18:29 UTC, pevisscher requested changes
See the comments

2022-02-17 21:12 UTC, MickVanDuijn commented on src/generator/cycle/cycle.ts
> +        consecutiveEmptyCycles = cycleSize === 0 ? consecutiveEmptyCycles + 1 : 0
this is not equivalent: my version is resetting the **consecutive** cycle count once a non-empty cycle has been detected

2022-02-17 21:40 UTC, MickVanDuijn commented on src/iterator/applicative/applicative.ts
> +    if (isArray(xs)) {
aye 😁 finding counter-examples has become a bit quicker and more memory efficient

2022-02-18 08:28 UTC, MickVanDuijn commented on src/random/types/mappable/mappable.ts
> +    return oneOf<Arbitrary<Mappable<T>>[]>(
in usage, you can now pass `array(unknown())` quite easily, which easily gives you full control over the array arbitrary params, but my main reason for implementing this was to make it re-entrant 🙊 so you could potentially have an `Arbitrary<Generator<T>>` and pass that in as well. This allows us to test basically all conversions between the different types by testing `mappable(mappable(array(unknown()))`

2022-02-18 09:17 UTC, MickVanDuijn commented on src/generator/cycle/cycle.ts
> +        consecutiveEmptyCycles = cycleSize === 0 ? consecutiveEmptyCycles + 1 : 0
(this code is removed in the last commit)

2022-02-18 09:17 UTC, MickVanDuijn commented on src/generator/cycle/cycle.ts
> +export function* cycle<T>(xs: Mappable<T>, maxConsecutiveEmptyCycles = 10000): InfiniteGenerator<T> {
👍 aaaaand it's gone!

2022-02-18 21:39 UTC, pevisscher approved these changes

2022-02-18 21:43 UTC, merged